import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css';
import { CartProvider } from './context/CartContext';
import Navbar from './components/navbar';
import Footer from './components/HomePage/Footer';
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'Hackathon Project',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* Navbar */}
          <CartProvider>
            <Navbar />
            <Toaster position="top-center" />
            {children}
            <Footer />
          </CartProvider>

        </body>
      </html>
    </ClerkProvider>
  );
}